name: Docker Image CI and Test

on:
  push:
    branches: [ docker-test ]
  pull_request:
    branches: [ master ]

env:
  # see the Dockerfile for the definition of some of the following environment variables
  status: alpha
  MBAS2024_REVENGER_TEST: 1
  download_data_dir: ${{ github.workspace }}/download_data
  output_dir: ${{ github.workspace }}/output
  mount_data_dir: /input
  mount_output_dir: /output
  revenger_data_dir: /challenge/cache/revenger_data_dir
  revenger_model_dir: /challenge/cache/revenger_model_dir
  docker_main_filename: Dockerfile
  data_gdrive_id: 1wCcU4DCwmSJHrv0h_6e7sRgK0D_PezAs
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_HUB_REPOSITORY: deeppsp-mbas2024-docker-image
  DOCKER_IMAGE_TAG: latest

jobs:

  build:
    if: contains(fromJson('["wenh06", "kjs11", "DeepPSP"]'), github.repository_owner)

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Clear unnecessary system components
      run: |
        echo "Free space before cleanup:"
        df -h
        sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
        sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        echo "Free space after cleanup:"
        df -h
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push the Docker image
      uses: docker/build-push-action@v2
      # build and push the Docker image, and keep the image in the cache
      with:
        context: .
        file: ${{ env.docker_main_filename }}
        push: ${{ github.event_name != 'pull_request' }}
        # load not used since docker/setup-buildx-action has set driver: docker instead of
        # the default driver: docker-container
        # set load true so that the image is kept in the cache and can be used in the next steps
        # load: true
        tags: |
          ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_HUB_REPOSITORY }}:${{ env.DOCKER_IMAGE_TAG }}

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Download the training data
      if: ${{ env.status != 'pre' }}
      # use gdown to download the training data
      run: |
        python -m pip install gdown
        mkdir -p ${{ env.download_data_dir }} ${{ env.output_dir }}
        gdown -O ${{ env.download_data_dir }}/MBAS2024.zip ${{ env.data_gdrive_id }}
        unzip ${{ env.download_data_dir }}/MBAS2024.zip -d ${{ env.download_data_dir }}
        rm ${{ env.download_data_dir }}/MBAS2024.zip
        rm -rf ${{ env.download_data_dir }}/__MACOSX
        du -sh ${{ env.download_data_dir }}

    - name: Run the Docker image
      # NOTE: mount env.download_data_dir to env.mount_data_dir
      # and set it read-only as in the CinC2024 challenge settings.
      # Also, the docker image is run without any internet access.
      if: ${{ env.status != 'pre' }}
      run: |
        docker images
        docker run \
          -e PYTHONUNBUFFERED=1 \
          -e MBAS2024_REVENGER_TEST=${{ env.MBAS2024_REVENGER_TEST }} \
          -e revenger_data_dir=${{ env.revenger_data_dir }} \
          -e revenger_model_dir=${{ env.revenger_model_dir }} \
          -e mount_data_dir=${{ env.mount_data_dir }} \
          -e mount_output_dir=${{ env.mount_output_dir }} \
          -v ${{ env.download_data_dir }}:${{ env.mount_data_dir }} \
          -v ${{ env.output_dir }}:${{ env.mount_output_dir }} \
          ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_HUB_REPOSITORY }}:${{ env.DOCKER_IMAGE_TAG }}
        docker ps -a
        ls -l ${{ env.output_dir }}
